#!/usr/bin/env python3
"""
memory-control-config test suite
=================================
Two test classes:

  DropInGenerationTests  - pure unit tests; no BMC / systemd required.
    Exercises the drop-in generation logic (size parsing, MemoryHigh
    calculation, OOM policy directives) using the same algorithm that
    memory-control-config_1.0.bb runs at do_install time.
    Runs on any host with Python 3.6+.

  OnTargetTests  - integration tests; run as root on the target.
    Verifies the drop-ins written into the real rootfs (under the systemd unit
    dir), that
    systemd has loaded every drop-in (MemoryMax matches), and that live
    cgroup memory usage is within safe bounds. Skipped automatically when
    systemctl / cgroup v2 are absent.

This recipe intentionally does NOT modify global kernel OOM policy
(e.g. vm.panic_on_oom), so there is deliberately no sysctl handling here.

Usage
-----
  # Unit tests only (host or target):
  python3 -m pytest tests/test_memory_control_config.py -v -k DropIn

  # All tests (target, run as root):
  python3 -m pytest tests/test_memory_control_config.py -v

  # Standalone (no pytest required):
  python3 tests/test_memory_control_config.py
"""

import configparser
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# The core drop-in generation logic, kept in lock-step with
# mc_parse_services()/do_install() in memory-control-config_1.0.bb so the unit
# tests exercise the same algorithm the recipe uses.

import re

SIZE_UNITS: Dict[str, int] = {
    "":  1,           "B":  1,
    "K": 1024,        "KB": 1024,
    "M": 1024 ** 2,   "MB": 1024 ** 2,
    "G": 1024 ** 3,   "GB": 1024 ** 3,
}

_SIZE_RE = re.compile(r"^(\d+)([A-Za-z]*)$")

# MemoryHigh is 70% of MemoryMax, computed with integer math to match the
# recipe exactly (bytes_max * 7 // 10).
def memory_high(bytes_max: int) -> int:
    return bytes_max * 7 // 10


class ConfigError(ValueError):
    """Raised for invalid MEMORY_CONTROL_SERVICES entries."""


def parse_limit(limit_str: str) -> int:
    """Convert a size string to bytes.

    Accepts raw integer bytes or a K/M/G[B] suffix (case-insensitive).
    Raises ConfigError on anything else (e.g. '1.5G', 'big', '12X').
    """
    limit_str = limit_str.strip()
    m = _SIZE_RE.match(limit_str)
    if not m:
        raise ConfigError(
            "limit '%s' is not a valid size (use raw bytes or a K/M/G[B] "
            "suffix)" % limit_str
        )
    number, suffix = m.group(1), m.group(2).upper()
    if suffix not in SIZE_UNITS:
        raise ConfigError(
            "unknown size suffix '%s' in '%s'" % (m.group(2), limit_str)
        )
    value = int(number) * SIZE_UNITS[suffix]
    if value <= 0:
        raise ConfigError("limit '%s' must be greater than zero" % limit_str)
    return value


def parse_entry(entry: str) -> Tuple[str, int, str]:
    """Parse one MEMORY_CONTROL_SERVICES entry.

    Returns (unit_name, bytes_max, oom_policy).
    Raises ConfigError on malformed input.
    """
    parts = entry.split(":")
    if not (2 <= len(parts) <= 3):
        raise ConfigError(
            "malformed entry '%s'; expected <unit>:<limit>[:<oom_policy>]"
            % entry
        )

    unit = parts[0].strip()
    if not unit.endswith(".service"):
        unit = unit + ".service"

    bytes_max = parse_limit(parts[1])

    oom_policy = parts[2].strip().lower() if len(parts) == 3 else "default"
    if oom_policy not in ("default", "kill"):
        raise ConfigError(
            "OOM policy '%s' for '%s' is invalid; use 'default' or 'kill'"
            % (oom_policy, unit)
        )

    return unit, bytes_max, oom_policy


def generate_dropin(destdir: str, entry: str) -> Path:
    """Write a single memory-control drop-in and return its Path."""
    unit, bytes_max, oom_policy = parse_entry(entry)
    bytes_high = memory_high(bytes_max)

    dropin_dir = Path(destdir).joinpath(*HOST_UNIT_SUBPATH, unit + ".d")
    dropin_dir.mkdir(parents=True, exist_ok=True)
    dropin_path = dropin_dir / "memory-control.conf"

    with dropin_path.open("w") as f:
        f.write("# generated by memory-control-config\n")
        f.write("# entry: %s\n" % entry)
        f.write("[Service]\n")
        f.write("MemoryMax=%d\n" % bytes_max)
        f.write("MemoryHigh=%d\n" % bytes_high)
        f.write("MemorySwapMax=0\n")
        if oom_policy == "kill":
            f.write("OOMPolicy=continue\n")
            f.write("OOMScoreAdjust=500\n")

    return dropin_path


def run_install(destdir: str, services_var: str) -> None:
    """Equivalent of the recipe's python do_install()."""
    for entry in services_var.split():
        generate_dropin(destdir, entry)


DROPIN_NAME = "memory-control.conf"

# The recipe installs into ${systemd_system_unitdir}. On the target that is
# /lib/systemd/system, or /usr/lib/systemd/system on usr-merged distros.

DROPIN_BASES = [
    Path("/usr/lib/systemd/system"),
    Path("/lib/systemd/system"),
    Path("/etc/systemd/system"),
]

# Path segments under the temp dir used by the host-side generator, mirroring
# ${systemd_system_unitdir} on a usr-merged target.
HOST_UNIT_SUBPATH = ("usr", "lib", "systemd", "system")


def read_dropin(path: Path) -> configparser.ConfigParser:
    """Return a ConfigParser loaded from a drop-in file."""
    parser = configparser.ConfigParser()
    parser.read_string(path.read_text())
    return parser


def _systemctl(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(["systemctl", *args], capture_output=True, text=True)


def _cgroup_v2_available() -> bool:
    try:
        result = subprocess.run(
            ["mount"], capture_output=True, text=True, check=True
        )
        return "cgroup2" in result.stdout
    except FileNotFoundError:
        return False


def _systemctl_available() -> bool:
    return shutil.which("systemctl") is not None


def _on_target() -> bool:
    return _systemctl_available() and _cgroup_v2_available()


def _installed_dropins() -> List[Path]:
    """Return all memory-control.conf drop-ins under any base systemd scans."""
    found: List[Path] = []
    for base in DROPIN_BASES:
        if base.is_dir():
            found.extend(base.glob("*.service.d/" + DROPIN_NAME))
    return sorted(found)


class DropInGenerationTests(unittest.TestCase):
    """Verify the drop-in generation logic without touching a real system."""

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp(prefix="mc_config_test_")

    def tearDown(self):
        shutil.rmtree(self.tmpdir, ignore_errors=True)


    def test_parse_limit_megabytes(self):
        self.assertEqual(parse_limit("512M"), 512 * 1024 ** 2)

    def test_parse_limit_kilobytes(self):
        self.assertEqual(parse_limit("256K"), 256 * 1024)

    def test_parse_limit_gigabytes(self):
        self.assertEqual(parse_limit("1G"), 1024 ** 3)

    def test_parse_limit_raw_bytes(self):
        self.assertEqual(parse_limit("536870912"), 536870912)

    def test_parse_limit_bytes_suffix(self):
        self.assertEqual(parse_limit("512B"), 512)

    def test_parse_limit_lowercase_suffix(self):
        self.assertEqual(parse_limit("512m"), 512 * 1024 ** 2)

    def test_parse_limit_kb_suffix(self):
        self.assertEqual(parse_limit("256KB"), 256 * 1024)

    def test_parse_limit_mb_suffix(self):
        self.assertEqual(parse_limit("512MB"), 512 * 1024 ** 2)

    def test_parse_limit_gb_suffix(self):
        self.assertEqual(parse_limit("2GB"), 2 * 1024 ** 3)

    def test_parse_limit_invalid_empty(self):
        with self.assertRaises(ConfigError):
            parse_limit("")

    def test_parse_limit_invalid_text(self):
        with self.assertRaises(ConfigError):
            parse_limit("big")

    def test_parse_limit_rejects_float(self):
        # A fractional size such as "1.5G" is a typo that must fail loudly,
        # never silently collapse to a tiny byte count.
        with self.assertRaises(ConfigError):
            parse_limit("1.5G")

    def test_parse_limit_rejects_unknown_suffix(self):
        with self.assertRaises(ConfigError):
            parse_limit("12X")

    def test_parse_limit_rejects_zero(self):
        with self.assertRaises(ConfigError):
            parse_limit("0")


    def test_parse_entry_two_parts(self):
        unit, bmax, policy = parse_entry("telemetry:512M")
        self.assertEqual(unit, "telemetry.service")
        self.assertEqual(bmax, 512 * 1024 ** 2)
        self.assertEqual(policy, "default")

    def test_parse_entry_three_parts_kill(self):
        _, _, policy = parse_entry("telemetry:512M:kill")
        self.assertEqual(policy, "kill")

    def test_parse_entry_three_parts_default(self):
        _, _, policy = parse_entry("telemetry:512M:default")
        self.assertEqual(policy, "default")

    def test_parse_entry_service_suffix_added(self):
        unit, _, _ = parse_entry("telemetry:512M")
        self.assertTrue(unit.endswith(".service"))

    def test_parse_entry_service_suffix_not_doubled(self):
        unit, _, _ = parse_entry("telemetry.service:512M")
        self.assertEqual(unit.count(".service"), 1)

    def test_parse_entry_too_few_parts(self):
        with self.assertRaises(ConfigError):
            parse_entry("telemetry")

    def test_parse_entry_too_many_parts(self):
        with self.assertRaises(ConfigError):
            parse_entry("a:b:c:d")

    def test_parse_entry_invalid_oom_policy(self):
        with self.assertRaises(ConfigError):
            parse_entry("telemetry:512M:panic")

    def test_parse_entry_policy_case_insensitive(self):
        _, _, policy = parse_entry("telemetry:512M:KILL")
        self.assertEqual(policy, "kill")


    def _gen(self, entry: str) -> Tuple[Path, configparser.ConfigParser]:
        path = generate_dropin(self.tmpdir, entry)
        return path, read_dropin(path)

    def test_dropin_file_created(self):
        path, _ = self._gen("telemetry:512M")
        self.assertTrue(path.exists())

    def test_dropin_filename(self):
        path, _ = self._gen("telemetry:512M")
        self.assertEqual(path.name, DROPIN_NAME)

    def test_dropin_parent_dir(self):
        path, _ = self._gen("telemetry:512M")
        self.assertEqual(path.parent.name, "telemetry.service.d")

    def test_dropin_has_service_section(self):
        _, cfg = self._gen("telemetry:512M")
        self.assertIn("Service", cfg)

    def test_dropin_memory_max_bytes(self):
        _, cfg = self._gen("telemetry:512M")
        self.assertEqual(int(cfg["Service"]["MemoryMax"]), 512 * 1024 ** 2)

    def test_dropin_memory_high_is_70_percent(self):
        _, cfg = self._gen("telemetry:512M")
        self.assertEqual(
            int(cfg["Service"]["MemoryHigh"]),
            memory_high(512 * 1024 ** 2),
        )

    def test_dropin_memory_high_less_than_max(self):
        _, cfg = self._gen("telemetry:512M")
        self.assertLess(
            int(cfg["Service"]["MemoryHigh"]),
            int(cfg["Service"]["MemoryMax"]),
        )

    def test_dropin_swap_disabled(self):
        _, cfg = self._gen("telemetry:512M")
        self.assertEqual(cfg["Service"]["MemorySwapMax"], "0")

    def test_dropin_default_policy_no_oom_directives(self):
        _, cfg = self._gen("telemetry:512M:default")
        self.assertNotIn("OOMPolicy", cfg["Service"])
        self.assertNotIn("OOMScoreAdjust", cfg["Service"])

    def test_dropin_kill_policy_oom_policy_continue(self):
        _, cfg = self._gen("telemetry:512M:kill")
        self.assertEqual(cfg["Service"]["OOMPolicy"], "continue")

    def test_dropin_kill_policy_oom_score_adjust(self):
        _, cfg = self._gen("telemetry:512M:kill")
        self.assertEqual(int(cfg["Service"]["OOMScoreAdjust"]), 500)

    def test_dropin_implicit_default_policy(self):
        _, cfg = self._gen("telemetry:512M")
        self.assertNotIn("OOMPolicy", cfg["Service"])


    def test_dropin_overwrite_on_rerun(self):
        generate_dropin(self.tmpdir, "telemetry:512M")
        path = generate_dropin(self.tmpdir, "telemetry:256M")
        cfg = read_dropin(path)
        self.assertEqual(int(cfg["Service"]["MemoryMax"]), 256 * 1024 ** 2)


    def test_run_install_empty_var(self):
        run_install(self.tmpdir, "")
        base = Path(self.tmpdir, *HOST_UNIT_SUBPATH)
        dropin_dirs = list(base.glob("*.d")) if base.exists() else []
        self.assertEqual(dropin_dirs, [])

    def test_run_install_multiple_services(self):
        run_install(
            self.tmpdir,
            "telemetry:512M:kill phosphor-health-monitor:128M",
        )
        base = Path(self.tmpdir).joinpath(*HOST_UNIT_SUBPATH)
        self.assertTrue((base / "telemetry.service.d" / DROPIN_NAME).exists())
        self.assertTrue(
            (base / "phosphor-health-monitor.service.d" / DROPIN_NAME).exists()
        )

    def test_run_install_whitespace_entries_skipped(self):
        run_install(self.tmpdir, "  telemetry:512M  ")
        base = Path(self.tmpdir).joinpath(*HOST_UNIT_SUBPATH)
        self.assertTrue((base / "telemetry.service.d" / DROPIN_NAME).exists())

    def test_run_install_memory_values_consistent(self):
        run_install(self.tmpdir, "bmcweb:256M:kill")
        dropin = (
            Path(self.tmpdir)
            .joinpath(*HOST_UNIT_SUBPATH)
            / "bmcweb.service.d"
            / DROPIN_NAME
        )
        cfg = read_dropin(dropin)
        self.assertEqual(int(cfg["Service"]["MemoryMax"]), 256 * 1024 ** 2)
        self.assertEqual(
            int(cfg["Service"]["MemoryHigh"]), memory_high(256 * 1024 ** 2)
        )

    def test_run_install_bad_entry_raises(self):
        with self.assertRaises(ConfigError):
            run_install(self.tmpdir, "telemetry:1.5G")


    def test_1k_limit(self):
        cfg = read_dropin(generate_dropin(self.tmpdir, "tiny:1K"))
        self.assertEqual(int(cfg["Service"]["MemoryMax"]), 1024)

    def test_1g_limit(self):
        cfg = read_dropin(generate_dropin(self.tmpdir, "big:1G"))
        self.assertEqual(int(cfg["Service"]["MemoryMax"]), 1024 ** 3)

    def test_raw_byte_limit(self):
        cfg = read_dropin(generate_dropin(self.tmpdir, "exact:1048576"))
        self.assertEqual(int(cfg["Service"]["MemoryMax"]), 1048576)



@unittest.skipUnless(
    _on_target(), "requires systemctl + cgroups v2 (run on target as root)"
)
class OnTargetTests(unittest.TestCase):
    """Verify the installed drop-ins and live systemd / kernel state."""

    @classmethod
    def setUpClass(cls):
        cls.dropins = _installed_dropins()


    def test_cgroup_v2_mounted(self):
        result = subprocess.run(["mount"], capture_output=True, text=True)
        self.assertIn(
            "cgroup2", result.stdout,
            "cgroups v2 not mounted - enable the unified hierarchy",
        )

    def test_memory_controller_available(self):
        controllers = Path("/sys/fs/cgroup/cgroup.controllers")
        self.assertTrue(
            controllers.exists(),
            "/sys/fs/cgroup/cgroup.controllers not found",
        )
        self.assertIn(
            "memory", controllers.read_text(),
            "'memory' controller absent - rebuild kernel with CONFIG_MEMCG=y",
        )


    def test_dropin_files_exist(self):
        if not self.dropins:
            self.skipTest(
                "no memory-control drop-ins found; "
                "MEMORY_CONTROL_SERVICES may have been empty"
            )

    def test_dropin_has_service_section(self):
        for dropin in self.dropins:
            with self.subTest(dropin=dropin):
                self.assertIn(
                    "Service", read_dropin(dropin),
                    "%s is missing [Service] section" % dropin,
                )

    def test_dropin_memory_max_is_positive_int(self):
        for dropin in self.dropins:
            with self.subTest(dropin=dropin):
                val = read_dropin(dropin)["Service"].get("MemoryMax", "")
                self.assertTrue(
                    val.isdigit() and int(val) > 0,
                    "%s: MemoryMax='%s' is not a positive integer"
                    % (dropin, val),
                )

    def test_dropin_memory_high_less_than_max(self):
        for dropin in self.dropins:
            with self.subTest(dropin=dropin):
                cfg = read_dropin(dropin)
                mem_max = int(cfg["Service"].get("MemoryMax", "0"))
                mem_high = int(cfg["Service"].get("MemoryHigh", "0"))
                self.assertGreater(mem_high, 0)
                self.assertLess(
                    mem_high, mem_max,
                    "%s: MemoryHigh (%d) must be < MemoryMax (%d)"
                    % (dropin, mem_high, mem_max),
                )

    def test_dropin_memory_high_is_70_percent(self):
        for dropin in self.dropins:
            with self.subTest(dropin=dropin):
                cfg = read_dropin(dropin)
                mem_max = int(cfg["Service"].get("MemoryMax", "0"))
                mem_high = int(cfg["Service"].get("MemoryHigh", "0"))
                self.assertEqual(
                    mem_high, memory_high(mem_max),
                    "%s: MemoryHigh=%d, expected %d (70%% of %d)"
                    % (dropin, mem_high, memory_high(mem_max), mem_max),
                )

    def test_dropin_swap_max_is_zero(self):
        for dropin in self.dropins:
            with self.subTest(dropin=dropin):
                self.assertEqual(
                    read_dropin(dropin)["Service"].get("MemorySwapMax"), "0",
                    "%s: MemorySwapMax must be 0" % dropin,
                )

    def test_dropin_kill_policy_directives(self):
        for dropin in self.dropins:
            cfg = read_dropin(dropin)
            if cfg["Service"].get("OOMPolicy") is None:
                continue
            with self.subTest(dropin=dropin):
                self.assertEqual(cfg["Service"]["OOMPolicy"], "continue")
                adj = cfg["Service"].get("OOMScoreAdjust", "")
                self.assertTrue(
                    adj.lstrip("-").isdigit(),
                    "%s: OOMScoreAdjust missing or non-integer" % dropin,
                )

    def test_dropin_permissions(self):
        for dropin in self.dropins:
            with self.subTest(dropin=dropin):
                mode = dropin.stat().st_mode & 0o777
                self.assertIn(
                    mode, (0o644, 0o640, 0o600),
                    "%s has unexpected permissions %o" % (dropin, mode),
                )


    def test_systemd_knows_each_unit(self):
        for dropin in self.dropins:
            unit = dropin.parent.name[: -len(".d")]
            with self.subTest(unit=unit):
                result = _systemctl("cat", unit)
                self.assertEqual(
                    result.returncode, 0,
                    "systemctl cat %s failed - run: systemctl daemon-reload"
                    % unit,
                )

    def test_systemd_memory_max_matches_dropin(self):
        for dropin in self.dropins:
            unit = dropin.parent.name[: -len(".d")]
            expected = int(read_dropin(dropin)["Service"]["MemoryMax"])
            with self.subTest(unit=unit):
                result = _systemctl("show", unit, "-p", "MemoryMax", "--value")
                sd = result.stdout.strip()
                if result.returncode != 0 or not sd.isdigit():
                    self.skipTest(
                        "%s: MemoryMax='%s' not numeric (unit may be masked)"
                        % (unit, sd)
                    )
                self.assertEqual(
                    int(sd), expected,
                    "%s: systemd MemoryMax=%s but drop-in says %d; run: "
                    "systemctl daemon-reload && systemctl restart %s"
                    % (unit, sd, expected, unit),
                )

    def test_systemd_memory_high_matches_dropin(self):
        for dropin in self.dropins:
            unit = dropin.parent.name[: -len(".d")]
            expected = int(read_dropin(dropin)["Service"]["MemoryHigh"])
            with self.subTest(unit=unit):
                result = _systemctl("show", unit, "-p", "MemoryHigh", "--value")
                if result.returncode != 0 or not result.stdout.strip().isdigit():
                    self.skipTest("MemoryHigh not available for %s" % unit)
                self.assertEqual(int(result.stdout.strip()), expected)


    def test_live_usage_within_safe_threshold(self):
        """Warn when a service is using more than 90% of its MemoryMax."""
        threshold = 0.90
        for dropin in self.dropins:
            unit = dropin.parent.name[: -len(".d")]
            if _systemctl("is-active", "--quiet", unit).returncode != 0:
                continue
            with self.subTest(unit=unit):
                cur = _systemctl("show", unit, "-p", "MemoryCurrent", "--value")
                mx = _systemctl("show", unit, "-p", "MemoryMax", "--value")
                cur_str, max_str = cur.stdout.strip(), mx.stdout.strip()
                if not (cur_str.isdigit() and max_str.isdigit()):
                    continue
                mem_cur, mem_max = int(cur_str), int(max_str)
                if mem_max == 0:
                    continue
                usage = mem_cur / mem_max
                self.assertLess(
                    usage, threshold,
                    "%s is using %.0f%% of MemoryMax (%d / %d bytes); the "
                    "limit may be too tight - consider raising it"
                    % (unit, usage * 100, mem_cur, mem_max),
                )

    def test_systemd_loaded_each_dropin(self):
        """systemd should list each installed drop-in in the unit's
        DropInPaths, confirming it is being read from a scanned location and
        not, e.g., stranded on a persist overlay that systemd ignores."""
        for dropin in self.dropins:
            unit = dropin.parent.name[: -len(".d")]
            with self.subTest(unit=unit):
                result = _systemctl("show", unit, "-p", "DropInPaths",
                                    "--value")
                if result.returncode != 0:
                    self.skipTest("DropInPaths not available for %s" % unit)
                loaded = result.stdout.split()
                self.assertIn(
                    str(dropin), loaded,
                    "%s not in DropInPaths for %s; systemd is not reading it "
                    "(wrong location or daemon-reload needed)" % (dropin, unit),
                )


if __name__ == "__main__":
    unittest.main(verbosity=2)